### ISSUE TITLE
Dashboard Sync Status does not match actual status

### ISSUE THREAD

**Issue by bigdaveakers** [NebraLtd/dashboard-issues#2]
**Describe the bug**
During initial setup the Dashboard Sync Status shows 100% despite the sync not being complete

**To Reproduce**
1. Boot Hotspot
2. Examine Hotspot on Nebra Dashboard

**Expected behavior**
Sync Status should be Out of Sync until unit actually syncs (matches the explorer status)

**Screenshots**
![image](https://user-images.githubusercontent.com/3410330/119813241-f0fd0e80-bee0-11eb-853f-e8ee310d3dae.png)
![image](https://user-images.githubusercontent.com/3410330/119813273-f9ede000-bee0-11eb-92a7-cdb9ffc91fdb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by walderston** [comment]
I too have this issue however its the other way around... 
Dashboard says syncing, both diagnostics page and helium explorer shows all synced. 

![image](https://user-images.githubusercontent.com/59405120/132137171-fa32b86f-e785-4d5b-a561-294c66a53f2a.png)
![image](https://user-images.githubusercontent.com/59405120/132137177-1153ae4c-e3b9-4d99-ba55-717842fc5133.png)
![image](https://user-images.githubusercontent.com/59405120/132137186-41884fe8-8aee-4f51-b9ab-0cd71ff4178e.png)

**Comment by ko2sec** [comment]
same here.

**Comment by vpetersson** [comment]
This is because the dashboard status is read from the Helium API (for now), whereas the local diagnostics status is read from the actual miner. Hence this is not a *bug* per se, but we are going to resolve this in the future.
