### ISSUE TITLE
Passwort reset link is incorrect

### ISSUE THREAD

**Issue by KevinWassermann94** [NebraLtd/dashboard-issues#22]
**Describe the bug**
When trying to do a passwort reset, the reset link is incorrect and is using the default template

**To Reproduce**
1. Go to https://dashboard.nebra.com/
2. Click on Forgotten Password
3. Receive the mail
4. The mail is using the standard template and the password reset link refers to example.com

**Expected behavior**
I expect to receive a mail with the correct link for a password reset

**Screenshots**
https://i.imgur.com/M57TOYL.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Newest

**Additional context**
Looks like the template just hasn't been adjusted

**Comment by vpetersson** [comment]
This has now been resolved.
