### ISSUE TITLE
Map in dashboard zoom level

### ISSUE THREAD

**Issue by bigdaveakers** [NebraLtd/dashboard-issues#3]
**Describe the bug**
The default zoom level in the map on the main dashboard page is too close

**To Reproduce**
1. Open Dashboard

**Expected behavior**
Expected to see an area around the hotspot but instead the level of zoom was about 5 metres x 5 meters

**Screenshots**
N/A due to privacy

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by vpetersson** [comment]
This has now been resolved.
