### ISSUE TITLE
Miner overview - Yesterday rewards incorrect

### ISSUE THREAD

**Issue by walderston** [NebraLtd/dashboard-issues#37]
**Describe the bug**
New miner which has just finished syncing with the network. Received the first reward however, the label in the overview says it is from yesterday.

**To Reproduce**
1. Go to `https://dashboard.nebra.com/`

**Expected behavior**
Either the label needs to be updated to 'Today' or how 'Yesterday' is being calculated is incorrect

**Screenshots**
![image](https://user-images.githubusercontent.com/59405120/132101721-4a79db8b-a10e-45ca-a8b2-450a20eef4a3.png)
![image](https://user-images.githubusercontent.com/59405120/132101727-746cbcf2-ee73-4b8e-b1a0-02926eed7877.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 92.0.4515.159

**Comment by vpetersson** [comment]
This has now been resolved.
