### ISSUE TITLE
Sync Percentage does not match between Dashboard and Local IP Diagnostics

### ISSUE THREAD

**Issue by fouad-semaan** [NebraLtd/dashboard-issues#39]
At least on my hotspot:

Local IP diag
![image](https://user-images.githubusercontent.com/38422316/134629547-66f61843-9f2e-42b2-ad08-74901afe9443.png)

Dashboard
![image](https://user-images.githubusercontent.com/38422316/134629612-510ae16f-742d-499a-abfd-bdaf080c8051.png)

**Comment by vpetersson** [comment]
This is expected. Basically, the local diagnostics pulls the data from the 'real' state, whereas the dashboard pulls this from the Helium API. As such, the latter will always have a lag.

We are reworking this, but it's expected for the time being.
