### ISSUE TITLE
Cannot change miner owner in Dashboard.

### ISSUE THREAD

**Issue by btothec** [NebraLtd/dashboard-issues#43]
**Describe the bug**
There is no way to change the owner and or register a currently registered miner in the nebra dashboard if bought second hand.

**To Reproduce**
Try and register a used miner at https://dashboard.nebra.com/
You will be given an error of "This device has already been claimed"

**Expected behavior**
The miner should be registered to your account.

**Additional context**
I realize that this is not the correct place for such a bug, but I have tried for weeks to get ahold of nebra using all other methods. Sorry.

**Comment by vpetersson** [comment]
Contact support@nebra.com to de-register the device from the previous owner.
