### ISSUE TITLE
During reboot or restart status is not updated

### ISSUE THREAD

**Issue by bigdaveakers** [NebraLtd/dashboard-issues#7]
**Describe the bug**
During a reboot or restart the dashboard and device manager do not reflect that the hotspot is undergoing these actions. It is therefore not possible to verify that the action has been performed.

**To Reproduce**
1. Select Reboot or Restart
2. Examine Dashboard and/or Device Manager
3. Observe that the status doesn't change and it appears that nothing is happening

**Expected behavior**
It would be expected that during a Reboot/Restart that the hotspot goes offline/unhealthy

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by vpetersson** [comment]
>> Expected behavior
> It would be expected that during a Reboot/Restart that the hotspot goes offline/unhealthy

No, this isn't the case. The status is not real time (neither on our side or on the Helium side). Thus, the device is likely to come back online before either system picks that the device is offline (in particular for an application restart).

That said, we are working on improving the notifications for this.
